"""empty message

Revision ID: 1ef21af010e
Revises: 8592b45ff0
Create Date: 2016-03-21 20:53:28.536498

"""

# revision identifiers, used by Alembic.
revision = '1ef21af010e'
down_revision = '8592b45ff0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
