"""empty message

Revision ID: 1f7c634fe36
Revises: 4427600f1a6
Create Date: 2016-03-21 10:18:20.198745

"""

# revision identifiers, used by Alembic.
revision = '1f7c634fe36'
down_revision = '4427600f1a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
