"""empty message

Revision ID: 3710dc089b8
Revises: 4ce60030020
Create Date: 2016-03-15 17:26:31.795912

"""

# revision identifiers, used by Alembic.
revision = '3710dc089b8'
down_revision = '4ce60030020'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', 'users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
