"""empty message

Revision ID: 4427600f1a6
Revises: 7d398c72b9
Create Date: 2016-03-20 21:35:12.756015

"""

# revision identifiers, used by Alembic.
revision = '4427600f1a6'
down_revision = '7d398c72b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photo_url', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photo_url')
    ### end Alembic commands ###
