"""empty message

Revision ID: 4f86606cd62
Revises: 3710dc089b8
Create Date: 2016-03-17 16:02:34.166876

"""

# revision identifiers, used by Alembic.
revision = '4f86606cd62'
down_revision = '3710dc089b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
