"""empty message

Revision ID: 8592b45ff0
Revises: 9edc88cca4
Create Date: 2016-03-21 16:02:34.835324

"""

# revision identifiers, used by Alembic.
revision = '8592b45ff0'
down_revision = '9edc88cca4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
