"""empty message

Revision ID: 9edc88cca4
Revises: 1f7c634fe36
Create Date: 2016-03-21 15:47:12.375610

"""

# revision identifiers, used by Alembic.
revision = '9edc88cca4'
down_revision = '1f7c634fe36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('disliker_id', sa.Integer(), nullable=True),
    sa.Column('disliked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disliked_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['disliker_id'], ['users.id'], )
    )
    op.create_table('likes',
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('dislikes')
    ### end Alembic commands ###
